### ISSUE TITLE
Add option to run without meta files

### ISSUE THREAD

**Issue by iaimmiac** [mar10/pyftpsync#19]
`.pyftpsync-meta.json` file is being added within each directory on remote. Please add a flag to remove this file on completion if it is needed for ftp sync.

**Comment by mar10** [comment]
This file (when stored on a remote FTP server) holds the real modification time of uploaded files.
We need this values to make file time comparisons, because FTP servers do not keep the time stamps, but set the upload time instead.
Currently I am working I am working on a refactoring (release 2.0) and I keep this issue open for now. Maybe there can be an option to do a naive sync without reliable the stamps.

**Comment by memiux** [comment]
Do the `.pyftpsync-meta.json` file really needs to be stored remotely on each directory?

I'm assuming that the actual persistence could be elsewhere, and that you just need some deltas in memory, so I don't know maybe you could use a small db with sqlite3 for all the remotes.

**Comment by gnanet** [comment]
I currently use pyftpsync to incremetally download a mailbox folder structure directly into a local mailbox folder, and if this metadata can speed up incremental functionality, i would not want them to be removed.

Instead i would welcome some option to tell pyftpsync where to replicate the folderstructure and place these metadata in the "shadow-folderstructure"

**or even better: if i could specify a meta-folder, where pyftpsync can store/look-for the meta files, and additionally the files could include their folder-path info, so there would be no need to create loads of folders.**

This meta-data-folder solution is applied for example in [offlineimap](https://github.com/OfflineIMAP/offlineimap/) as a config value called [metadatadir](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/CustomConfig.py#L93)

**Comment by gnanet** [comment]
Gerne, hab aber mit rsync exclude von lokal zu lokal die mailfiles nach dem ftpsync gelöst ;)

**Comment by FloridaStream** [comment]
+1 for this @mar10 
it would be nice to have a single metadata file in the home, and also the option to customize its name.
would avoid creating multiple metadatas in each directory, would love to have that option. it would be visually more organized with that.
