### ISSUE TITLE
Messages should not be printed to stdout when used as a library

### ISSUE THREAD

**Issue by SeanDS** [mar10/pyftpsync#22]
It'd be nice if the library printed messages/errors via the standard Python `logging` module. Right now, the library prints to `stdout` in all circumstances, which bypasses logging functionality (and goes against the [common practice of libraries not printing to `stdout`](http://docs.python-guide.org/en/latest/writing/logging/)).

As you already use the `_log_action` method for all print messages, it would be straightforward to change the `print(...)` statement within it to use instead the logging system, and enable a stream handler pointed at `stdout` for the command line interface.

**Comment by mar10** [comment]
Thanks for bringing this up. 
My main personal use case is the CLI, where stdout / stderr are reasonable targets, for example to support redirection and piping. We also make use of ansi codes for colors and progress output.
But I agree that this is mostly not wanted when used as a library, so it should be controllable.
(Interestingly, the standard Python `ftplib` uses `print` in debug mode.)
