### ISSUE TITLE
Download Synchronizer tries to upload when local file is older than remote

### ISSUE THREAD

**Issue by romankor** [mar10/pyftpsync#23]
I think there is bug , the Download synchronizer tries to upload to remote an older local file, unless i don't get and it should be like that , but the remote should be not writable at all when using the Download Syncronizer
```python
    def sync_older_local_file(self, local_file, remote_file):
        if self._check_del_unmatched(local_file):
            return False
        self._log_action("copy", "modified", "<", local_file)
        self._copy_file(self.local, self.remote, remote_file)
```

should be the opposite i guess
```python
    def sync_older_local_file(self, local_file, remote_file):
        if self._check_del_unmatched(local_file):
            return False
        self._log_action("copy", "modified", "<", local_file)
        self._copy_file(self.remote, self.local, remote_file)
```

**Comment by mar10** [comment]
Which version are you using?
2.0 is available as beta candidate, so you could help testing this version (note however that the meta file formats are incompatible, so it should not be in production. You also need to pass `––pre` to pip)

**Comment by romankor** [comment]
Yes was using 1.0.x .. 
Looks working in the 2.0.0 , will use it

**Comment by mar10** [comment]
Thanks for the feedback
