### ISSUE TITLE
'new' not supported in interactive resolve in the DownloadSyncronizer

### ISSUE THREAD

**Issue by romankor** [mar10/pyftpsync#25]
I think there is a bug in the download syncronizer.
It allows only for ``` assert resolve in ("remote", "ask", "skip")```
Then what we get in the ```on_conflict``` method is : 
```python
            elif resolve == "remote" or (is_newer and resolve == "old") or \
                    (not is_newer and resolve == "new"):
                self._log_action("copy", "conflict", "*<*", pair.local)
                self._copy_file(self.remote, self.local, pair.remote)
```
Which clearly just copies every files again and again since i kinda need to use `remote` all the time

**Comment by mar10** [comment]
`resolve` is meant to resolve a conflict situation.

  - If only the remote file is newer, 
     => no conflict, we simply copy to local
  - If only the local file is newer,
     => no conflict, but we skip the entry because in download mode remote is read-only
     The --force option can be used copy remote to local instead
  - If both files are modified ('conflict') and the remote file is newer, 
     --resolve=remote will copy
     This would be the same effect as --resolve=new
  - If both files are modified ('conflict') and the local file is newer, 
     --resolve=remote will replace the newer with the older
     --resolve=new would have no effect, since remote is read-only => this would leave the entry unresolved
  - If both files are unmodified (the most common case probably)
     => no copying at all

Could you explain in which scenario you think there are missing options or too much copying?

**Comment by mar10** [comment]
We can re-open this if I better understand the request.
