### ISSUE TITLE
Crash when not setting verbose option

### ISSUE THREAD

**Issue by frozax** [mar10/pyftpsync#26]
The following line should be a `options.get` 

https://github.com/mar10/pyftpsync/blob/6711f2ff48944f30ff3fa413291dd6a6cc0dee0b/ftpsync/synchronizers.py#L167

**Comment by mar10** [comment]
Thanks!

**Comment by pg** [comment]
I was just using version 3.1.0, and this still seems to be a problem.

```
util.py, line 211, in get_credentials_for_url
    verbose = int(opts.get("verbose"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
