### ISSUE TITLE
exclude directories does when pyftpsync is used within a script for upload

### ISSUE THREAD

**Issue by benbkk2** [mar10/pyftpsync#28]
exclude file does work as expected
exclude directory does work when pyftpsync is called from a shell

**Comment by mar10** [comment]
Hi,
can you give more details and a code snippet of what you tried?

**Comment by benbkk2** [comment]
Hi, I have tried to reproduce the issue without success... Sorry for disturbing.
Congrats for this good piece of software. A documentation about the messages displayed would be very useful, as well as an example on how to log them in a file. 
Thank you

**Comment by mar10** [comment]
Thanks, I adddes some docs:
http://pyftpsync.readthedocs.io/en/latest/user_guide.html#logging
