### ISSUE TITLE
application error with msi installer

### ISSUE THREAD

**Issue by ThetomekK** [mar10/pyftpsync#29]
Hi,

i installed the msi version "pyftpsync-2.0.0-win32.msi". That worked, but calling "pyftpsync --help" in command promt, a application error window pops up: Error Code 0xc000007b: application couldn't be started correctly.

![pyftpsync_app_error](https://user-images.githubusercontent.com/6866371/37405073-9642201a-278b-11e8-96c5-c375b262b5df.JPG)

Any advice on that?

Thanks in advance

**Comment by ThetomekK** [comment]
Could this be associated with my system?

![system infos](https://user-images.githubusercontent.com/6866371/37405254-11d16484-278c-11e8-8d59-2a3904fa2252.JPG)

**Comment by mar10** [comment]
I just re-installed on Win10 from here https://github.com/mar10/pyftpsync/releases/tag/v2.0.0
and it seems to run. 
What Windows version are you on? Does it happen on other computers as well?
Googling for "0xc00007b" finds some hints, that DLLs may be missing...
