### ISSUE TITLE
[v2.0] exclude files

### ISSUE THREAD

**Issue by Squale76** [mar10/pyftpsync#31]
Hi, I tried to use your very good script in mine to update my web site.
But I can't use exclude option.
When I try :
```
local = FsTarget( path_TmpGIT )
remote = FtpTarget("/", ftpHOST, username=ftpUSER, password=ftpPASS)
opts = {"force": True, "delete_unmatched": True, "verbose": 5, "no_color": True}
s = UploadSynchronizer(local, remote, opts)
s.run()
```
My .git folder is upload despite the default option. And when i tried, it's not better : 
```
local = FsTarget( path_TmpGIT )
remote = FtpTarget("/", ftpHOST, username=ftpUSER, password=ftpPASS)
opts = {"force": True, "delete_unmatched": True, "verbose": 5, "no_color": True, "exclude": ".git"}
s = UploadSynchronizer(local, remote, opts)
s.run()
```

**Comment by mar10** [comment]
The default excludes (['.DS_Store', '.git', '.hg', '.svn']) are currently only applied by the CLI, not when running as library script. I just tested this, and it seemed to work:
```py
local = FsTarget("/path1")
remote = FsTarget("/path2")
opts = {
    "verbose": 5,
    "dry_run": True,
    "exclude": ".git",
    }
s = UploadSynchronizer(local, remote, opts)
s.run()
```
The local path contains a `.git` folder, and the output shows:
```
INFO:pyftpsync:(DRY-RUN) SKIP UNMATCHED    -  [.git]          
```
Can you post your output, or even set a breakpoint to see what's happening?
