### ISSUE TITLE
[suggestion] list of compatible ftp daemon

### ISSUE THREAD

**Issue by iapyeh** [mar10/pyftpsync#37]
The pyftpsync is excellent. But the MLSD command is not implemented widely. At this moment, the results of google searching is not informative. It took me about 4 hours to figure out "pure-ftpd" works.  I almost once gave up pyftpsync because that I thought there is no any linux ftpd supports MLSD.

Maybe it is worthy to have a compatible list of ftpd somewhere in the documentation.

**Comment by mar10** [comment]
Could you post the results of your investigations?
This could be a good starting point!
