### ISSUE TITLE
Unable to navigate to working directory '/hetznertet' (now at '/hetznertet/')

### ISSUE THREAD

**Issue by trubrek** [mar10/pyftpsync#38]
While i tried to upload my directory to cdn push zone over FTP i geting this error
Unable to navigate to working directory '/hetznertet' (now at '/hetznertet/')

cdn zone patch is /hetznertet/ so as target i used cdn.com/hetznertet/ i tried cdn.com/hetznertet as well, but it give same errror

**Comment by mar10** [comment]
Are you sure that “ hetznertet” is correct?
Please post the complete output in —verbose mode.
Did you try other ftp clients?

**Comment by trubrek** [comment]
[11:28][root@server.beuwo.com ~]# pyftpsync scan ftp://het:psw@storage.bunnycdn.com/hetznertet/
INFO:keyring.backend:Loading KWallet
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading Windows
INFO:keyring.backend:Loading chainer
INFO:keyring.backend:Loading macOS
Setting FTP encoding to utf-8 (was latin-1).
Traceback (most recent call last):
  File "/usr/local/bin/pyftpsync", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/ftpsync/pyftpsync.py", line 204, in run
    return args.command(parser, args)
  File "/usr/local/lib/python3.6/site-packages/ftpsync/scan_command.py", line 82, in scan_handler
    target.open()
  File "/usr/local/lib/python3.6/site-packages/ftpsync/ftp_target.py", line 254, in open
    self.root_dir, pwd
RuntimeError: Unable to navigate to working directory '/hetznertet' (now at '/hetznertet/')


i tried ftp over mobaxterm and its working 
yes /hetznertet/ is correct this is copy paste lication from their site i am not sure if that / must be at end because mobaxterm do 
<<<  250 directory changed to /hetznertet/
Directory /hetznertet/ opened. Showing file list...

**Comment by mar10** [comment]
The FTP `PWD` command returned a trailing `/`, which was not expected and causes the sanity check to fail.
