### ISSUE TITLE
problem with old server ftp

### ISSUE THREAD

**Issue by guisz1** [mar10/pyftpsync#40]
I have an old server where it does not cover MLSD, but I need to synchronize in the normal way

**Comment by mar10** [comment]
Sorry, but this not supported.

**Comment by guisz1** [comment]
well, I took advantage of the time I had and modified the library to obtain the same data from the LIST command

**Comment by mar10** [comment]
If you have a robust implementation, that supports the different response format, feel free to open a pull request.
