### ISSUE TITLE
Unable to navigate to working directory '' (Windows)

### ISSUE THREAD

**Issue by yanek** [mar10/pyftpsync#5]
Both the local and remote computers are running on Windows 7. Running the script like that:

```python
import pyftpsync.targets
import pyftpsync.ftp_target
import pyftpsync.synchronizers

local = pyftpsync.targets.FsTarget("temp")
user = "my_user"
passwd = "my_pass"
remote = pyftpsync.ftp_target.FtpTarget("/", "0.0.0.0", 18416, user, passwd)
opts = {
    "resolve": "remote",
    "verbose": 3,
    "dry_run": False
}
s = pyftpsync.synchronizers.DownloadSynchronizer(local, remote, opts)
s.run()
```
...and it gives me an RuntimeError: 
> Unable to navigate to working directory ""

Nothing changes if `path = ''\\"` or `path = "."`.

So I made a dirty and personal fix in [ftp_target.py](https://github.com/mar10/pyftpsync/blob/master/ftpsync/ftp_target.py#L107-L109) file (line 107 to 109) :
```python
pwd = self.root_dir
# if pwd != self.root_dir:
#    raise RuntimeError("Unable to navigate to working directory %r" % self.root_dir)
```
Now it's working the way I wanted, but I think there may be a proper fix.

**Comment by mar10** [comment]
thanks!
