### ISSUE TITLE
how to make the program keep running and monitoring

### ISSUE THREAD

**Issue by amorsu** [mar10/pyftpsync#50]
I have two FTP servers need to sync with each other, and I run pyftpsync on my computer as a middle point, how to keep the program running so if each FTP server have file modification, it will be sync to the other FTP server immediately. I think of a scheduled task but if it's a big file that will take some time, how will I set the timing? if there is a build-in feature for this? thanks!

**Comment by mar10** [comment]
Sorry, no built-in feature for this yet. Running a shell script regularly may be a good approach.
(You might also consider to ask on Stackoverflow.)
