### ISSUE TITLE
Error downloading or syncing some specific folders sftp

### ISSUE THREAD

**Issue by mrprobz** [mar10/pyftpsync#56]
Hi, Im using your pyftpsync tool to sync a remote sftp to an other machine.
This seemed to be working fine until it stopped at a certain folder.. No clue why this folder specifically.
I have tried syncing individual folders instead of syncing the entire tree.. this worked for some folders but not for all. And now i noticed it would also stop after x amount of files.
Any ideas?

**Comment by mar10** [comment]
Hard to tell, but maybe you getsome hints when running with increased verositiy (`-vvv`)
