### ISSUE TITLE
download copies older local file in wrong direction

### ISSUE THREAD

**Issue by Paul424** [mar10/pyftpsync#6]
When i run pyftpsync --verbose --progress download <local-path> <remote-path> -x (where the remote is a readonly ftp target) then an error is hit saying the dest is readonly (duhhh). I believe the error is in synchronizers.py line 981. The implementation of sync_older_local_file for DownloadSynchronizer should be:

def sync_older_local_file(self, local_file, remote_file):
        if self._check_del_unmatched(local_file):
            return False
        self._log_action("copy", "modified", "<", local_file)
        self._copy_file(self.remote, self.local, remote_file)

and not:

def sync_older_local_file(self, local_file, remote_file):
        if self._check_del_unmatched(local_file):
            return False
        self._log_action("copy", "modified", "<", local_file)
        self._copy_file(self.local, self.remote, remote_file)

**Comment by mar10** [comment]
Closed by #7, thanks
