### ISSUE TITLE
Cant use this if build app use pyinstaller --windowed mode

### ISSUE THREAD

**Issue by AnyOfYou** [mar10/pyftpsync#60]
Hi, thanks for this project.

I found that I can't use this module(version 3.1.0) if my app is builded by pyinstaller --windowed. I can run my app directly with command "python app.py".

I catch the exception:

File "ftpsync\util.py", line 104, in <module>
OSError: [WinError 6] The handle is invalid

That line 104 in ftpsync\util.py is "IS_REDIRECTED = os.fstat(0) != os.fstat(1)", I change that to "IS_REDIRECTED = False" for temporary workaround.

**Comment by mar10** [comment]
Thanks for reporting. Would you mind to open a PR that catches the exception and uses the fallback?

**Comment by AnyOfYou** [comment]
Sure, glad to do that. Will open a PR soon.
