### ISSUE TITLE
Bidirectional sync over FTPS doesn't delete folders

### ISSUE THREAD

**Issue by dfrison01** [mar10/pyftpsync#71]
Platform: Win10 / Python 3.7
Pyftpsync v: 3.1.0

Hi! Sorry if this is not a bug, but running the bidirectional sync on cmd does not remove directories (local or remote) that have been deleted since last sync. It actually tries to copy again the deleted folder. I found this very odd and decided to report. Am I doing something wrong?

CMD example: `pyftpsync sync "{local}" "ftps://{USR}:{PSW}@{SERVER}:{PORT}/{remote}" --resolve=new --progress`

Again, I'm sorry if this is the normal behaviour! At least that's not what I expected, and couldn't find anything about it in the docs. I can supply more details as needed. Thanks!

**Comment by mar10** [comment]
Could you construct a minimal example (small folder structure), that demonstrates the problem and share the command line and log file, when running in verbose mode?

**Comment by dfrison01** [comment]
Hi @mar10! Thank you for your time. I'm sorry, but I don't know how to get the mentioned "log file", can you please point me where it's stored?

About the folder structure. Assuming a root dir called "Test" on the local client:

Test\
├── logs\
├── imges\
└── rsc\

If I delete the "logs" directory, then do
'pyftpsync sync "C:\Test" "ftps://remote/Test" --resolve=new --progress'
I get the message "COPYING NEW  --<--  logs", instead of the deletion of the dir on the remote machine.
Is that clear? Sorry for the missing log file, just point me to it and I'll post it here.
Thanks again!
