### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by EnricoBeltramo** [mar10/pyftpsync#72]
I'm looking for this library, but I have some trouble to find clear examples. I need to sync two folders  in backbround. There exist a no blocking run() version of bidirectional sync? After set a source and dest to sync, is it possible to stop the sync and restart it with another couple of source and destination?

**Comment by mar10** [comment]
`run()` is blocking [see the example](https://pyftpsync.readthedocs.io/en/latest/user_guide.html#script-examples).

You could run it inside a separate thread, of course.
There is currently no way to stop `run()` from an external thread, but you could implement it in a custom class that is derrived from the synchronizer and overrides `_tick()`  for example.
