### ISSUE TITLE
Support for SSH key pairs

### ISSUE THREAD

**Issue by JoeZiminski** [mar10/pyftpsync#75]
Thanks for this excellent package for syncing folder trees, it is exactly what we need for our project.

We want to use the private_key argument on pysftp.Connection for SSH key pairs previously configured using paramiko. I am planning to fork the repo and implement this, if it will be useful I am happy to do it as a PR, or maybe there is aready a way to do this that I have missed (we are planning to provide cross-platform support so would rather avoid using system keyrings).

**Comment by mar10** [comment]
Hi Joe,

these arguments to `pysftp.Connection` are currently not used, but it would certainly be a good enhancement!
