### ISSUE TITLE
python 3.5 types

### ISSUE THREAD

**Issue by Nikovit** [mar10/pyftpsync#9]
I use python 3.5, the error types

> Traceback (most recent call last):
>   File "/home/r1ka/backup.py/PostgreSQL_bacup2.py", line 58, in <module>
>     s = BiDirSynchronizer(local, remote, opts)
>   File "/home/r1ka/backup.py/ftpsync/synchronizers.py", line 535, in __init__
>     super(BiDirSynchronizer, self).__init__(local, remote, options)
>   File "/home/r1ka/backup.py/ftpsync/synchronizers.py", line 66, in __init__
>     remote.open()
>   File "/home/r1ka/backup.py/ftpsync/ftp_target.py", line 88, in open
>     self.ftp.connect(self.host, self.port)
>   File "/usr/local/lib/python3.5/ftplib.py", line 146, in connect
>     if port > 0:
> TypeError: unorderable types: str() > int()

**Comment by mar10** [comment]
Could you try to replace 
```py
        if self.port:
            self.ftp.connect(self.host, self.port)
        else:
            self.ftp.connect(self.host)
```
with
```py
        if self.port:
            self.ftp.connect(self.host, int(self.port))
        else:
            self.ftp.connect(self.host)
```
and let us know if it works (or even create a pull request)?

**Comment by Nikovit** [comment]
does not work:

> Traceback (most recent call last):
>   File "/home/r1ka/backup.py/PostgreSQL_bacup2.py", line 102, in <module>
>     s = BiDirSynchronizer(local, remote, opts)
>   File "/home/r1ka/backup.py/ftpsync/synchronizers.py", line 535, in __init__
>     super(BiDirSynchronizer, self).__init__(local, remote, options)
>   File "/home/r1ka/backup.py/ftpsync/synchronizers.py", line 66, in __init__
>     remote.open()
>   File "/home/r1ka/backup.py/ftpsync/ftp_target.py", line 88, in open
>     self.ftp.connect(self.host, int(self.port))
> ValueError: invalid literal for int() with base 10: 'user'

**Comment by mar10** [comment]
Seems you're passing "user" instead of a port
Can you post your code?

**Comment by Nikovit** [comment]
I give an example of how to http://pyftpsync.readthedocs.io/en/latest/

My code: https://github.com/Nikovit/backup/blob/master/PostgreSQL_bacup2.py

**Comment by mar10** [comment]
The signature is described here
http://pyftpsync.readthedocs.io/en/latest/ftpsync.html#module-ftpsync.ftp_target
but the tutorial was misleading:
You were passing the username for the port.
