### ISSUE TITLE
How to handle special characters in password?

### ISSUE THREAD

**Issue by ChillarAnand** [mar10/pyftpsync#92]
```
❯ pyftpsync download . sftp://anand:abc=.d[[&@avilpage.com/ 
```
This command is failing as the above URI is invalid. However, passing encoded password is failing as ftpsync is not decoding it.

**Comment by mar10** [comment]
Does #89 help?

**Comment by ChillarAnand** [comment]
I don't think that works when urlparse itself fails. 

I am using with the following fix, and it seems to be working fine.

https://github.com/ChillarAnand/pyftpsync/commit/2d7559802e3b2c3fee47c1242538bf89b58e3ab8

**Comment by mar10** [comment]
Thanks, If you submit I PR I will include with the next release

**Comment by ChillarAnand** [comment]
Raised PR for the same.

https://github.com/mar10/pyftpsync/pull/93/files
